version: '3.8'

services:
  app:
    build: .
    container_name: legacy_recipe_app
    #load environment variables
    env_file:
      - .env
    volumes:
      #map inventory file from the host machine, to make sure it updates without needing to re-build the image
      - ./inventory.txt:/app/inventory.txt
   #expose port 5000
    expose:
      - "5000"

  #proxy settings
  proxy:
    image: nginx:alpine
    container_name: legacy_home_proxy
    ports:
      - "80:80" #expose container port 80 to host port 80
    volumes:
      #include settings file in the Nginx proxy
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      #include dashboard file, into the folder that Nginx uses
      - ./index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - app #make sure that the python app runs before the Nginx proxy