server {
    listen 80;

    # הגשת הדאשבורד הסטטי כשנכנסים ל-localhost
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # ניתוב בקשות API לקונטיינר של אפליקציית הפייתון
    location /api {
        # 'app' הוא השם שניתן לשירות של הפייתון בקובץ ה-compose
        proxy_pass http://app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}