server {
    listen 80;
    #provide the static dashboard when entering the localhost
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    #navigate API request to the container of the python app.
    location /api {
        #compose is the name that is given for the python service in the app file
        proxy_pass http://app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}